language: python
python: '3.7'
dist: xenial
sudo: true
cache: pip
before_install:
- pip install poetry
install:
- poetry install -v
script:
- pytest --cov
after_success:
- codecov
notifications:
  email:
    on_success: change
    on_failure: always
