language: python
python:
- '3.8'
- "3.9-dev"
- nightly
os: linux
dist: bionic
cache: pip
before_install:
- pip install poetry
install:
- poetry install -v
script:
- pytest --cov
after_success:
- codecov
