[tool.poetry]
name = "carscanner"
version = "0.1.0"
description = "Car offer scanner"
authors = ["Rafal Krupinski <rkrupinski+github@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
mattes-allegro-pl = "^0.4.0"
CherryPy = "^18.1"
PyYAML = "^5.1"
tinydb = "^3.13"
ujson = "^1.35"
unidecode = "^1.0"

[tool.poetry.dev-dependencies]
pytest = "^4.4"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
