[tool.poetry]
name = "carscanner"
version = "1.2.3"
description = "Car offer scanner"
authors = ["Matte Silver"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"
mattes-allegro-pl = "^0.7.0"
CherryPy = "^18.1"
PyYAML = "^5.1"
tinydb = "^3.13"
ujson = "^1.35"
unidecode = "^1.0"

[tool.poetry.dev-dependencies]
codecov = "^2.0"
pytest = "^4.4"
pytest-cov = "^2.7"
toml = "^0.10.0"

[tool.poetry.scripts]
carscanner = 'carscanner.cmd:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
